# Generated by Django 2.2.2 on 2023-07-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomApp', '0002_answer_category_question_quizzes'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default=models.CharField(max_length=255, unique=True), max_length=100, null=True),
        ),
    ]
